/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import dao.daoEmpleado;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Personal;

/**
 *
 * @author HJVM
 */
public class ActualizarEmpleado extends javax.swing.JFrame {

    DefaultTableModel model;

    daoEmpleado daoE = new daoEmpleado();
    Personal pEscogido = null;

    /**
     * Creates new form ActualizarEmpleado
     */
    public ActualizarEmpleado() {
        initComponents();
        model = (DefaultTableModel) tableEmpleados.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoEmpleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmpleados = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProceso = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblDatosEmpleado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCodigoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoEmpleadoKeyReleased(evt);
            }
        });

        jLabel1.setText("Código Empleado:");

        btnMostrarTodos.setText("Mostrar Todos");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        tableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Empleado", "Código de Ficha", "Nombres", "Apellidos", "Proceso", "Área", "Contraseña"
            }
        ));
        tableEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEmpleados);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Proceso:");

        jLabel3.setText("Area:");

        jLabel4.setText("Empleado Seleccionado:");

        jLabel5.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarTodos)
                .addGap(0, 212, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArea))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDatosEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passContra, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDatosEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTabla() {
        model.setRowCount(0);

        for (Personal p : daoE.listarEmpleados()) {
            String[] arreglo = new String[7];
            arreglo[0] = String.valueOf(p.getCodEmpeado());
            arreglo[1] = p.getCodFichaEmpleado();
            arreglo[2] = p.getNombreEmpleado();
            arreglo[3] = p.getApellidoEmpleado();
            arreglo[4] = p.getProceso();
            arreglo[5] = p.getAreaEmpleado();
            arreglo[6] = p.getPasswordEmpleado();

            model.addRow(arreglo);
        }

        txtCodigoEmpleado.setText("");
    }

    private void buscar() {
        model.setRowCount(0);
        if (!txtCodigoEmpleado.getText().equals("")) {
            for (Personal p : daoE.listarEmpleados()) {
                if (p.getCodFichaEmpleado().contains(txtCodigoEmpleado.getText())) {
                    String[] arreglo = new String[7];
                    arreglo[0] = String.valueOf(p.getCodEmpeado());
                    arreglo[1] = p.getCodFichaEmpleado();
                    arreglo[2] = p.getNombreEmpleado();
                    arreglo[3] = p.getApellidoEmpleado();
                    arreglo[4] = p.getProceso();
                    arreglo[5] = p.getAreaEmpleado();
                    arreglo[6] = p.getPasswordEmpleado();

                    model.addRow(arreglo);
                }
            }
        }
        tableEmpleados.setModel(model);
    }

    private void txtCodigoEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEmpleadoKeyReleased
        buscar();
    }//GEN-LAST:event_txtCodigoEmpleadoKeyReleased

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void tableEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmpleadosMouseClicked
        txtCodigoEmpleado.requestFocus();
        String cod = model.getValueAt(tableEmpleados.getSelectedRow(), 1).toString();
        txtCodigoEmpleado.setText(cod);
        pEscogido = daoE.buscarEmpleado(cod);
        buscar();
        lblDatosEmpleado.setText(retornaDatosEmpleado(pEscogido));

        asignarDatosTXT(pEscogido);

    }//GEN-LAST:event_tableEmpleadosMouseClicked

    private void asignarDatosTXT(Personal p) {
        txtArea.setText(p.getAreaEmpleado());
        txtProceso.setText(p.getProceso());
        passContra.setText(p.getPasswordEmpleado());
    }

    private String retornaDatosEmpleado(Personal p) {
        return p.getCodEmpeado() + " - " + p.getCodFichaEmpleado() + " - " + p.getNombreEmpleado() + "  &  " + p.getApellidoEmpleado() + " - " + p.getProceso() + " - " + p.getAreaEmpleado() + " - " + p.getPasswordEmpleado();
    }

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        if (!lblDatosEmpleado.getText().equals("")) {
            String pass = String.valueOf(passContra.getPassword());
            String proceso = txtProceso.getText();
            String area = txtArea.getText();

            pEscogido.setPasswordEmpleado(pass);
            pEscogido.setProceso(proceso);
            pEscogido.setAreaEmpleado(area);

            daoE.actualizarEmpleado(pEscogido);
            clearDatos();
            txtCodigoEmpleado.setText(pEscogido.getCodFichaEmpleado());
            vaciarTabla();
            buscar();
            limpiarObjeto();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un empleado para actualizar.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void clearDatos() {
        txtArea.setText("");
        txtCodigoEmpleado.setText("");
        txtProceso.setText("");
        passContra.setText("");
    }

    private void vaciarTabla() {
        model.setRowCount(0);
    }

    private void limpiarObjeto() {
        pEscogido = null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatosEmpleado;
    private javax.swing.JPasswordField passContra;
    private javax.swing.JTable tableEmpleados;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCodigoEmpleado;
    private javax.swing.JTextField txtProceso;
    // End of variables declaration//GEN-END:variables
}
